name: Drakkar Import Wizard Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tags para rodar os testes'
        required: false
        default: ''

permissions:
  contents: write
  pages: write

jobs:
  test:
    timeout-minutes: 60  
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up test data
        run: |
          if [ ! -f helper/util/test-data/registerUser.json ]; then
            mkdir -p helper/util/test-data
            echo "{\"userName\":\"${{ secrets.USER_NAME }}\", \"password\":\"${{ secrets.PASSWORD }}\"}" > helper/util/test-data/registerUser.json
          fi

      - name: Setup Node.js and Playwright
        run: |
          npx playwright install --with-deps
          npm ci

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}-${{ hashFiles('package.json') }}-${{ matrix.node-version }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-

      - name: Ensure test-results directory exists
        run: mkdir -p test-results

      - name: Set environment variables for tests
        run: |
          echo "BASEURL=${{ secrets.BASEURL }}" >> $GITHUB_ENV
          echo "ENV=test" >> $GITHUB_ENV

      - name: Ensure .env file is available
        run: |
          mkdir -p helper/env
          echo "BASEURL=${{ secrets.BASEURL }}" > helper/env/.env.dev
          echo "ENV=test" >> helper/env/.env.dev

      - name: Run Cucumber tests
        run: |
          if [ -z "${{ github.event.inputs.tags }}" ]; then
            npm test
          else
            npm test --TAGS="${{ github.event.inputs.tags }}"
          fi
        env:
          BASEURL: ${{ secrets.BASEURL }}
          ENV: test
          npm_config_TAGS: "${{ github.event.inputs.tags }}"
        shell: bash

      - name: Upload Cucumber Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cucumber-test-report
          path: test-results
          retention-days: 5

  deploy-report:
    needs: test
    runs-on: ubuntu-22.04
    steps:
      - name: Download Test Report
        uses: actions/download-artifact@v4
        with:
          name: cucumber-test-report
          path: test-results

      - name: Rename Cucumber Report to index.html
        run: cp test-results/cucumber-report.html test-results/index.html

      - name: Ensure JSON is accessible
        run: cp test-results/cucumber-report.json test-results/report.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: test-results
          publish_branch: gh-pages
          force_orphan: true
          allow_empty_commit: true
